name: Publish to PyPI

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "**/pyproject.toml"

jobs:
  publish:
    strategy:
      matrix:
        runs-on: [ubuntu-latest]
        python-version: ["3.10"]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install poetry
      - name: Download models from HuggingFace
        run: |
          git clone https://huggingface.co/wildsonbbl/gnnepcsaft  hfdata
          cp hfdata/*.onnx* ./gnnepcsaft_mcp_server/models
      - name: Publish to PyPI
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish --build
