name: Publish to PyPI

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "**/pyproject.toml"

jobs:
  publish:
    strategy:
      matrix:
        runs-on: [ubuntu-latest]
        python-version: ["3.10"]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Download models from HuggingFace
        run: |
          git clone https://huggingface.co/wildsonbbl/gnnepcsaft  hfdata
          cp hfdata/*.onnx* ./gnnepcsaft_mcp_server/models
      - name: Publish to PyPI
        run: |
          uv build
          uv publish --trusted-publishing always
